[tool.poetry]
name = "fastapi-alembic-postgres"
version = "0.1.0"
description = ""
authors = ["Quien Sabe <qs5779@mail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
sqlalchemy = "^2.0.11"
alembic = "^1.10.4"
fastapi = "^0.95.1"


[tool.poetry.group.test.dependencies]
isort = "^5.12.0"
black = "^23.3.0"
pytest = "^7.3.1"
wemake-python-styleguide = "^0.17.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
