version: 2

updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      time: "01:15"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "01:15"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10
