"""User table

Revision ID: 2f61a2b01346
Revises: 6f0a5bde4076
Create Date: 2023-05-10 12:50:01.111973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f61a2b01346'
down_revision = '6f0a5bde4076'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jail')
    op.drop_table('banned')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('addr', sa.VARCHAR(length=39), nullable=False),
    sa.Column('jail_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['jail_id'], ['jail.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
