"""Initial Revision

Revision ID: 6f0a5bde4076
Revises:
Create Date: 2023-05-01 11:21:30.285091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0a5bde4076'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('addr', sa.String(length=39), nullable=False),
    sa.Column('jail_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jail_id'], ['jail.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banned')
    op.drop_table('jail')
    # ### end Alembic commands ###
